
# tasks file for roles/proxy
- name: Run database
  docker_container: 
    name: database
    image: romyn/some-postgres #nom sur docker hub
    networks: 
      - name: app-network
    env:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd