
# tasks file for roles/proxy
- name: Run database
  docker_container: 
    name: database #nom du docker container
    image: romyn/some-postgres #nom sur docker hub
    networks: 
      - name: app-network #tous dans le même network
    env: #variables d'environnement de connexion à la bdd
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
