# tasks file for roles/proxy
- name: Run proxy 
  docker_container: 
    name: proxy 
    image: romyn/httpd #nom sur docker hub
    networks: 
      - name: app-network #tous sur le même network
    ports: 80:80 #port de l'affichage
