name: CI devops 2022 CPE

on:
  #to begin you want to launch this job in main and develop
  push:
    branches: master
  pull_request:


jobs:
  backend:
    #version sur lequel le job va run
    runs-on: ubuntu-18.04
    # sequence de taches qui vont être execute
    steps:
      - uses: actions/checkout@v2
    
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
              java-version: '11'
              distribution: 'adopt' 

      - name: Build and test with Maven
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  #On rajoute ce token car il y a une erreur sinon
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        #run: mvn clean verify --file ./Backend/simple-api2 #chemin de POM.xml, la ou on execute la commande
        run: mvn -B verify sonar:sonar -Dsonar.projectKey=RomynRoy_DEVOPS2 -Dsonar.organization=romynroy2 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{secrets.SONAR_TOKEN }} --file ./Backend/simple-api2/pom.xml
  build-and-push-docker-image:
    needs: backend
    # run lorsque la compilation et les tests sont finis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_TOKEN}} #permet de se loggin à docker avec nos mdp secret que l'on a ajoutés à GitHub

      - name: Build image and push backend
        uses: docker/build-push-action@v2
        with:
          # chemin du dockerfile de backend
          context: ./Backend
          tags: ${{secrets.DOCKERHUB_USERNAME}}/backend #le nom du backend enregistré sur docker
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Build image and push database
        uses: docker/build-push-action@v2
        with:
          context: ./Database # chemin du dockerfile de la bdd 
          tags: ${{secrets.DOCKERHUB_USERNAME}}/some-postgres #le nom de la bdd enregistré sur docker
          push: ${{ github.ref == 'refs/heads/master' }}
      - name: Build image and push httpd
        uses: docker/build-push-action@v2
        with:
          context: ./http_serveur # chemin du dockerfile de serveur web
          tags: ${{secrets.DOCKERHUB_USERNAME}}/httpd #le nom du serveur web enregistré sur docker
          push: ${{ github.ref == 'refs/heads/master' }}
    
