# This is a basic workflow to help you get started with Actions

name: CI devops 2022 CPE

# Controls when the workflow will run
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: [ main ] #TODO
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
     # run: echo Hello, world!

      #do the same with another action (actions/setup-java@v2) that enable to setup jdk 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
          
      #finally build your app with the latest command
      - name: Build and test with Maven
          run:[maven]
